const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="damiruimo@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Colombo";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "94768806865";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94743747913";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "true"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "truw" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "image" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "unavailable" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_05_53_07_20_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTMxLFxuICAgICAgICA3OSxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMjAsXG4gICAgICAgIDg1LFxuICAgICAgICAyMTksXG4gICAgICAgIDQ3LFxuICAgICAgICAxMzMsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMDAsXG4gICAgICAgIDYsXG4gICAgICAgIDQ3LFxuICAgICAgICA1NSxcbiAgICAgICAgMjA3LFxuICAgICAgICA1OSxcbiAgICAgICAgOTgsXG4gICAgICAgIDY3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTYyLFxuICAgICAgICAxMjUsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjMsXG4gICAgICAgIDg1LFxuICAgICAgICA2OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MSxcbiAgICAgICAgMTc4LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTgsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTM5LFxuICAgICAgICA4MCxcbiAgICAgICAgMjAzLFxuICAgICAgICA1MSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxMzAsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTMxLFxuICAgICAgICAxMTIsXG4gICAgICAgIDQ5LFxuICAgICAgICA0OCxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDExMixcbiAgICAgICAgMTc2LFxuICAgICAgICA5NCxcbiAgICAgICAgNDAsXG4gICAgICAgIDE4NixcbiAgICAgICAgOTEsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTYyLFxuICAgICAgICAxNTcsXG4gICAgICAgIDIyLFxuICAgICAgICAyNDEsXG4gICAgICAgIDUxLFxuICAgICAgICA0NFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMyLFxuICAgICAgICA2MCxcbiAgICAgICAgMTQ2LFxuICAgICAgICA4LFxuICAgICAgICAxNDIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjAyLFxuICAgICAgICAzMCxcbiAgICAgICAgMjAxLFxuICAgICAgICA4NCxcbiAgICAgICAgMjIwLFxuICAgICAgICA1OCxcbiAgICAgICAgOTcsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNjcsXG4gICAgICAgIDI0MixcbiAgICAgICAgODEsXG4gICAgICAgIDg2LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIxLFxuICAgICAgICAxOTksXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMDQsXG4gICAgICAgIDMsXG4gICAgICAgIDMwLFxuICAgICAgICA4MSxcbiAgICAgICAgNzksXG4gICAgICAgIDE2MCxcbiAgICAgICAgMzcsXG4gICAgICAgIDEyM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNSxcbiAgICAgICAgODgsXG4gICAgICAgIDEsXG4gICAgICAgIDQxLFxuICAgICAgICA1LFxuICAgICAgICAxNTYsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjE5LFxuICAgICAgICAyNyxcbiAgICAgICAgMTA0LFxuICAgICAgICA5MSxcbiAgICAgICAgMTgxLFxuICAgICAgICAxMixcbiAgICAgICAgMTU5LFxuICAgICAgICAyMTEsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTg0LFxuICAgICAgICA3MSxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDc0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMzksXG4gICAgICAgIDIzMixcbiAgICAgICAgNTYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMzIsXG4gICAgICAgIDkyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDAsXG4gICAgICAgIDIzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTc3LFxuICAgICAgICAyMDMsXG4gICAgICAgIDExNyxcbiAgICAgICAgOTUsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTc5LFxuICAgICAgICA2OSxcbiAgICAgICAgMTMwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTk3LFxuICAgICAgICAxNjgsXG4gICAgICAgIDcsXG4gICAgICAgIDUxLFxuICAgICAgICAyNDMsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMDIsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNjEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjQ4LFxuICAgICAgICA2MCxcbiAgICAgICAgMjA3LFxuICAgICAgICA1OSxcbiAgICAgICAgODAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTA0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQwLFxuICAgICAgICA4MCxcbiAgICAgICAgNjcsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjU0LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTMzLFxuICAgICAgICA4OSxcbiAgICAgICAgMTc1LFxuICAgICAgICA4MSxcbiAgICAgICAgMjUwLFxuICAgICAgICA5NSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMjgsXG4gICAgICAgIDE0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDcxLFxuICAgICAgICA5MyxcbiAgICAgICAgMjMzLFxuICAgICAgICAxNTUsXG4gICAgICAgIDE5MixcbiAgICAgICAgNjgsXG4gICAgICAgIDE0LFxuICAgICAgICA3MCxcbiAgICAgICAgMjUsXG4gICAgICAgIDc1LFxuICAgICAgICAxNjIsXG4gICAgICAgIDgwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgODdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgOThcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3NSxcbiAgICAgICAgNjksXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNTksXG4gICAgICAgIDczLFxuICAgICAgICA0NixcbiAgICAgICAgMjAxLFxuICAgICAgICAyNDQsXG4gICAgICAgIDg3LFxuICAgICAgICAxOTMsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxODQsXG4gICAgICAgIDY5LFxuICAgICAgICA3OSxcbiAgICAgICAgNjcsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTExLFxuICAgICAgICAxMzQsXG4gICAgICAgIDYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTcxLFxuICAgICAgICAyNDMsXG4gICAgICAgIDU1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNixcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMjYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTg5LFxuICAgICAgICAyNDksXG4gICAgICAgIDIwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTQ1LFxuICAgICAgICAyLFxuICAgICAgICAyMzcsXG4gICAgICAgIDIxLFxuICAgICAgICAxNzgsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTQsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNjYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMzMsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjcsXG4gICAgICAgIDg4LFxuICAgICAgICAzNixcbiAgICAgICAgMjM3LFxuICAgICAgICAyNTAsXG4gICAgICAgIDEyOCxcbiAgICAgICAgNzQsXG4gICAgICAgIDIxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTE5LFxuICAgICAgICA3XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA3MyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJSajRtRlVCdjkrL0xpbUJaakM3NC85eGhMemcvQTBTeU9UZUhKMHM1NFBNPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzQzNzQ3OTEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0ODAxMDZBMEI1NDZFMDE3Mzc3NTJGQjFGQTJDNTc1RlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjE0NTQ4MTJcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiTzJVWDJDU1pTekdOSmJKU0M0em5lQVwiLFxuICBcInBob25lSWRcIjogXCIyNDE2NWM4Yi1iNzc0LTQ0MjYtYTBmOC05MDAxODZiNGE5NTFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTAxLFxuICAgICAgMTc3LFxuICAgICAgMTk4LFxuICAgICAgOTksXG4gICAgICAxODYsXG4gICAgICAyMjMsXG4gICAgICAxNjEsXG4gICAgICAxODUsXG4gICAgICAxNTYsXG4gICAgICAyMSxcbiAgICAgIDIwNCxcbiAgICAgIDk0LFxuICAgICAgMjQ5LFxuICAgICAgMjE2LFxuICAgICAgODksXG4gICAgICAyNixcbiAgICAgIDIyLFxuICAgICAgMjI0LFxuICAgICAgMTIsXG4gICAgICAyNTJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDIwOSxcbiAgICAgIDIxNyxcbiAgICAgIDg5LFxuICAgICAgMTgyLFxuICAgICAgNDMsXG4gICAgICAyNTUsXG4gICAgICAxMzAsXG4gICAgICAxNDksXG4gICAgICAxNjMsXG4gICAgICAxNDAsXG4gICAgICAxMDUsXG4gICAgICAxMDksXG4gICAgICA2MCxcbiAgICAgIDE1NCxcbiAgICAgIDg4LFxuICAgICAgNDcsXG4gICAgICAyNyxcbiAgICAgIDQ3LFxuICAgICAgNDksXG4gICAgICAxNVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tTQ3c1Z0VFTlNoN2JRR0dBb2dBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwicnJsN1JGQ3pnQVJVT29JcVFVcFdUOURYS3owdndhS20yem5rTWVWZWlsdz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCIzS0VaRDkwMXBrVkJUZ0xocy95SURVVUpSalZacVJZTkxyMEd2cXYvanpUanpMeTYwYVZkS251R2tOUjJ3Z3d3YTFBaEtMSlVSM2xPT3VzYmJFdlZDdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJDc3YzcFVtaFJvMmh2dGlxN2haVWZPa2FEVUEydDRCZDIyblZBQVFraVdmQUZyK3BjTG9HZ2lwNTU5UXZmb0ZQZy9uTy92Tm9qbXl0SUlrUzdZOTVEQT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzQzNzQ3OTEzOjQwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxMzgwMTA2ODc0NDcyNTc6NDBAbGlkXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDc0Mzc0NzkxMzo0MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgNCxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgOTJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMTQ1NDgwNyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQU1XVFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTVdULmpzb24iOiAie1wia2V5RGF0YVwiOlwiWTdIaWV1VTdRM0VyMDBjQ3h6eDhJZVB5RTNPeHJ1djZzY292NUY1OTVHdz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1MTcxNDkyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFNV1UuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJQMm1teTVZSFZ6Z2ZibURJME01VWI2VGFaL1RUbXpHellVRU9CMVRXTXRjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjUxNzE0OTIsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMiw0XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFNV1YuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJKQUtZQWRvV0htOVlqTzVyYlI4SC9tSStwSU1GQ012UHNkSDZxa2wvaWxRPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjUxNzE0OTIsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMiw1XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFNV1cuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJqMmQ2RVpSSUpZRGFQZmdRby9hekwwc3hVZ1FCNER2QUxLSDg3d05XdDdFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjUxNzE0OTIsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzIxMTQzMDQ5MjAzXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTVdYLmpzb24iOiAie1wia2V5RGF0YVwiOlwienoxRm05RkpoM08rR1drK3pvckZKK1hRVFE0T1ZjNGFRSzhBRllVWkUycz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1MTcxNDkyLFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMCwxLDIsNl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTVdZLmpzb24iOiAie1wia2V5RGF0YVwiOlwiS2ozVlFXL2VmdGNYa2F2WEp0amMrd3cwNThmbW9pNTY2SkdiN25lWjZtOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1MTcxNDkyLFwiY3VycmVudEluZGV4XCI6OCxcImRldmljZUluZGV4ZXNcIjpbMCwxLDIsNl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTVdaLmpzb24iOiAie1wia2V5RGF0YVwiOlwiOHNIS1Z1ei9jQ2VGSFR2RWtFQnUycFQxekNSMmRsNUxqZ3hsNTNTV3Y2WT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI1MTcxNDkyLFwiY3VycmVudEluZGV4XCI6OSxcImRldmljZUluZGV4ZXNcIjpbMCwxLDIsNl19LFwidGltZXN0YW1wXCI6XCIxNzIxNDU0MjE3ODcxXCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
